oauth-server-address: 'https://eu1.cloud.thethings.network/oauth'
identity-server-grpc-address: 'eu1.cloud.thethings.network:8884'

gateway-server-grpc-address: 'au1.cloud.thethings.network:8884'
network-server-grpc-address: 'au1.cloud.thethings.network:8884'
application-server-grpc-address: 'au1.cloud.thethings.network:8884'
join-server-grpc-address: 'au1.cloud.thethings.network:8884'
device-claiming-server-grpc-address: 'au1.cloud.thethings.network:8884'
device-template-converter-grpc-address: 'au1.cloud.thethings.network:8884'
qr-code-generator-grpc-address: 'au1.cloud.thethings.network:8884'

